### ISSUE TITLE
Minor bug in Markdown output

### ISSUE THREAD

**Issue by sloanthrasher** [zzzprojects/sqlfiddle3#2]
In the markdown output, there is a small bug. There is no extra line following the "RESULTS" line, so the tabular output in the markdown isn't rendered properly in StackoverFlow when pasted in an answer. It's easily fixed after pasting by added a blank line, but I thought you might want to update the output.

**Comment by JonathanMagnan** [comment]
Hello @sloanthrasher ,

You are right, we will look at it for the release this Friday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @Jon,

This issue will be closed since it has been solved and in prod since several days.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
